# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    xcode_select("/Applications/Xcode_16.4.app")

    setup_ci

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: ENV["APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64"]
    )

    produce(
      username: ENV["APPLE_ID"],
      app_identifier: "com.dcr3.logseq",
      app_name: "Logseq DCR3",
      language: "English",
      app_version: '2.0',
      sku: 'com.dcr3.logseq.main'
      enable_services: {
        app_group: "on",
        icloud: "xcode6_compatible",
        push_notification: "on"
      }
    )

    sync_code_signing(type: "appstore", readonly: false)

    build_number = increment_build_number(
      xcodeproj: "App.xcodeproj",
      build_number: latest_testflight_build_number + 1,
    )

    # Ref: https://docs.fastlane.tools/advanced/fastlane/#directory-behavior
    sh("../../../scripts/patch-xcode-project.sh")

    build_app(
      workspace: "App.xcworkspace",
      destination: "generic/platform=iOS",
      scheme: "Logseq",
      configuration: "Release",
    )

    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true,
    )

    # slack(message: "App Build (#{build_number}) successfully uploaded to TestFlight 🎉!")
  end
end
